Resolve OpenSSL Build Error on aarch64
# Update openssl

RUN apk add --no-cache \

 openssl=3.3.3-r0

fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz
ERROR: unable to select packages:
openssl-3.3.4-r0:
breaks: world[openssl=3.3.3-r0]